platform :ios, '15.0'

require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

target 'CocoapodsInstallationTest' do
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'RevenuecatPurchasesCapacitor', :path => '../../'
  pod 'RevenuecatPurchasesCapacitorUi', :path => '../../purchases-capacitor-ui'
end